"""LangGraph state definition for the multi-agent research pipeline."""

from typing import TypedDict, Optional
from langgraph.graph import add_messages


class ResearchState(TypedDict):
    """Shared state passed between all agents in the research graph.

    Attributes:
        topic: The user-provided research topic.
        subtasks: List of focused subtasks generated by the Planner.
        research_results: List of dicts with keys 'subtask', 'synthesis', and 'sources'.
        critique: Textual critique from the Critic agent.
        needs_more_research: Flag set by the Critic to trigger a retry loop.
        retry_count: Number of research retries performed so far.
        final_report: The finished markdown report produced by the Writer.
        sources: Aggregated list of source dicts with 'title' and 'url'.
        current_agent: Name of the currently executing agent (for UI updates).
        log: List of human-readable log strings displayed in the UI.
    """

    topic: str
    subtasks: list[str]
    research_results: list[dict]
    critique: Optional[str]
    needs_more_research: bool
    retry_count: int
    final_report: Optional[str]
    sources: list[dict]
    current_agent: str
    log: list[str]
